// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgQdMCxp4k0yxOLs4s7_SfhPYkbrZgH70',
    appId: '1:898648695070:web:a507bbaa21688c89f3a90f',
    messagingSenderId: '898648695070',
    projectId: 'auth-ec7d5',
    authDomain: 'auth-ec7d5.firebaseapp.com',
    storageBucket: 'auth-ec7d5.appspot.com',
    measurementId: 'G-S5K7HNJZ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIBbHqIcpl8pUYLiaDFTM-_esv7xDQrU',
    appId: '1:898648695070:android:eaaf2afcc26a9a20f3a90f',
    messagingSenderId: '898648695070',
    projectId: 'auth-ec7d5',
    storageBucket: 'auth-ec7d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVIOHJ56VnAqGG3K8BXcd93XCI05Xi0g',
    appId: '1:898648695070:ios:23505f9de2a10fbef3a90f',
    messagingSenderId: '898648695070',
    projectId: 'auth-ec7d5',
    storageBucket: 'auth-ec7d5.appspot.com',
    iosBundleId: 'com.example.h14barad',
  );

}